"""Add e new table

Revision ID: 07deec6b14b3
Revises: 20e9ec7788a8
Create Date: 2023-08-19 01:04:41.046332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07deec6b14b3'
down_revision = '20e9ec7788a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pdf_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('excel_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('files_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('files_filename')
        batch_op.drop_column('excel_filename')
        batch_op.drop_column('pdf_filename')
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
