"""Initial migration

Revision ID: 20e9ec7788a8
Revises: 2194fde35115
Create Date: 2023-08-09 00:47:49.998369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e9ec7788a8'
down_revision = '2194fde35115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_add_post', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_update_post', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_delete_post', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('can_delete_post')
        batch_op.drop_column('can_update_post')
        batch_op.drop_column('can_add_post')

    # ### end Alembic commands ###
