"""Initial migration

Revision ID: 2194fde35115
Revises: ef7de83b15df
Create Date: 2023-08-08 23:54:16.859091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2194fde35115'
down_revision = 'ef7de83b15df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_superuser')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superuser', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
